import type { Metadata } from "next";
import "./globals.css";
import Headers from "@/components/Header";
import { Toaster } from "react-hot-toast";
import {Providers} from "@/Providers"


export const metadata: Metadata = {
  title: "Ecommerece Platform",
  description: "Generated by Deepak Singh",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      
       <Providers>
          <Headers/>
          {children}
          <Toaster position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
