import type { Metadata } from "next";
import "./globals.css";
import Headers from "@/components/Header";


export const metadata: Metadata = {
  title: "Ecommerece Platform",
  description: "Generated by Deepak Singh",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Headers/>
      <main>{children}</main> 
      </body>
    </html>
  );
}
