import type { Metadata } from "next";
import "./globals.css";
import Headers from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Headers/>
      <main>{children}</main> 
      </body>
    </html>
  );
}
